export const operadores =[
      {
            id: 1,
            status: 'disponivel',
            foto: 'img1.jpg',
            nome: 'Alberto Valentin',
            email:'alberto.valentin@vendas.com',
            contato: '48 9 88365255',
            horario_inicio: '07:30',
            horario_fim: '15:30',
            tma: 18.2,
            media_vendas: 83535.02 
      },
      {
            id: 2,
            status: 'disponivel',
            foto: 'img2.jpg',
            nome: 'Alana Silva',
            email:'alana.silva@vendas.com',
            contato: '48 9 99352684',
            horario_inicio: '07:30',
            horario_fim: '15:30',
            tma:  19.5,
            media_vendas: 99556.21
      },
      {
            id: 3,
            status: 'disponivel',
            foto: 'img3.jpg',
            nome: 'Rafael Siqueira',
            email:'rafael.siqueira@vendas.com',
            contato: '48 9 88326589',
            horario_inicio: '07:30',
            horario_fim: '13:30',
            tma: 18.1,
            media_vendas: 55468.65
      },
      {
            id: 4,
            status: 'disponivel',
            foto: 'img4.jpg',
            nome: 'Rosangela Almeida',
            email:'rosangela.almeida@vendas.com',
            contato: '48 9 91542886',
            horario_inicio: '07:30',
            horario_fim: '13:30',
            tma: 21.32,
            media_vendas: 55692.32
      },
      {
            id: 5,
            status: 'atestado',
            foto: 'img5.jpg',
            nome: 'Sandro Guilherme de Souza',
            email:'sandro.souza@vendas.com',
            contato: '48 9 91542468',
            horario_inicio: '08:00',
            horario_fim: '16:00',
            tma: 17.32,
            media_vendas: 98692.32
      },
      {
            id: 6,
            status: 'disponivel',
            foto: 'img6.jpg',
            nome: 'Gustavo Martins',
            email:'gustavo.martins@vendas.com',
            contato: '48 9 88272886',
            horario_inicio: '08:00',
            horario_fim: '16:00',
            tma: 19.55,
            media_vendas: 95625.82
      },

      {
            id: 7,
            status: 'atestado',
            foto: 'img7.jpg',
            nome: 'Maria Aparecida Souza',
            email:'maria.aparecida@vendas.com',
            contato: '48 9 99305544',
            horario_inicio: '08:00',
            horario_fim: '14:00',
            tma: 17.08,
            media_vendas: 57362.32
      },
      {
            id: 8,
            status: 'ferias',
            foto: 'img8.jpg',
            nome: 'Samathan Bitencourt',
            email:'samathan.bitencourt@vendas.com',
            contato: '48 9 99782586',
            horario_inicio: '08:30',
            horario_fim: '14:30',
            tma: 19.52,
            media_vendas: 62398.17
      },
      {
            id: 9,
            status: 'disponivel',
            foto: 'img9.jpg',
            nome: 'Sarah Alcantra',
            email:'sarah.alcantra@vendas.com',
            contato: '48 9 88112886',
            horario_inicio: '08:30',
            horario_fim: '14:30',
            tma: 18.25,
            media_vendas: 51322.53
      },
      {
            id: 10,
            status: 'disponivel',
            foto: 'img10.jpg',
            nome: 'Sandro Drummont',
            email:'sandro.drummont@vendas.com',
            contato: '48 9 22879564',
            horario_inicio: '08:30',
            horario_fim: '16:30',
            tma: 19.32,
            media_vendas: 98478.67
      },
      {
            id: 11,
            status: 'ferias',
            foto: 'img11.jpg',
            nome: 'Leticia Colin',
            email:'leticia.colin@vendas.com',
            contato: '48 9 86522886',
            horario_inicio: '08:30',
            horario_fim: '16:30',
            tma: 17.32,
            media_vendas: 77692.32
      },
      {
            id: 12,
            status: 'disponivel',
            foto: 'img12.jpg',
            nome: 'Fabio Caetano',
            email:'fabio.caetano@vendas.com',
            contato: '48 9 99535886',
            horario_inicio: '09:00',
            horario_fim: '15:00',
            tma: 18.32,
            media_vendas: 51752.32
      },
      {
            id: 14,
            status: 'disponivel',
            foto: 'img14.jpg',
            nome: 'Juliana Santos',
            email:'juliana.santos@vendas.com',
            contato: '48 9 99535886',
            horario_inicio: '09:00',
            horario_fim: '17:00',
            tma: 17.98,
            media_vendas: 99350.65
      },
      {
            id: 15,
            status: 'disponivel',
            foto: 'img15.jpg',
            nome: 'Bruna Camargo Melo',
            email:'bruna.melo@vendas.com',
            contato: '48 9 88412578',
            horario_inicio: '09:00',
            horario_fim: '17:00',
            tma: 19.67,
            media_vendas: 102752.32
      },
      {
            id: 16,
            status: 'disponivel',
            foto: 'img16.jpg',
            nome: 'Anna Santos Braga',
            email:'anna.braga@vendas.com',
            contato: '48 9 993265886',
            horario_inicio: '10:00',
            horario_fim: '18:00',
            tma: 19.32,
            media_vendas: 115899.32
      },
      {
            id: 17,
            status: 'ferias',
            foto: 'img17.jpg',
            nome: 'Carol Ribeiro Silva',
            email:'carol.riveiro@vendas.com',
            contato: '48 9 88546986',
            horario_inicio: '10:00',
            horario_fim: '18:00',
            tma: 18.85,
            media_vendas: 108811.40
      },
      {
            id: 18,
            status: 'disponivel',
            foto: 'img18.jpg',
            nome: 'Martha Oliveira',
            email:'martha.oliveira@vendas.com',
            contato: '48 9 88652314',
            horario_inicio: '12:00',
            horario_fim: '20:00',
            tma: 21.22,
            media_vendas: 128811.40
      },
      {
            id: 19,
            status: 'ferias',
            foto: 'img19.jpg',
            nome: 'Renan Santos Correia',
            email:'renan.santos@vendas.com',
            contato: '48 9 88254614',
            horario_inicio: '12:00',
            horario_fim: '20:00',
            tma: 23.22,
            media_vendas: 145811.40
      },
      {
            id: 20,
            status: 'disponivel',
            foto: 'img20.jpg',
            nome: 'Maria Tereza Lisboa',
            email:'maria.lisboa@vendas.com',
            contato: '48 9 88658214',
            horario_inicio: '14:00',
            horario_fim: '22:00',
            tma: 19.22,
            media_vendas: 105201.40
      },
      {
            id: 21,
            status: 'disponivel',
            foto: 'img21.jpg',
            nome: 'Breno Oliveira',
            email:'breno.olivaira@vendas.com',
            contato: '48 9 99654517',
            horario_inicio: '14:00',
            horario_fim: '22:00',
            tma: 19.22,
            media_vendas: 93201.40
      },
      {
            id: 22,
            status: 'disponivel',
            foto: 'img22.jpg',
            nome: 'Luana Cristina Santos',
            email:'luana.santos@vendas.com',
            contato: '48 9 91568919',
            horario_inicio: '14:00',
            horario_fim: '22:00',
            tma: 21.22,
            media_vendas: 87201.40
      }
      
]